//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Models
{
   public partial class Article1С
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Article1С()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="_title"></param>
      /// <param name="_sourse"></param>
      /// <param name="_editdata"></param>
      /// <param name="_significancecoefficient"></param>
      /// <param name="_isdeleted"></param>
      /// <param name="_article1с0"></param>
      /// <param name="_articletag1"></param>
      public Article1С(string _title, string _sourse, DateTime _editdata, double _significancecoefficient, bool _isdeleted, Models.Article1С _article1с0, Models.ArticleTag _articletag1)
      {
         if (string.IsNullOrEmpty(_title)) throw new ArgumentNullException(nameof(_title));
         Title = _title;
         if (string.IsNullOrEmpty(_sourse)) throw new ArgumentNullException(nameof(_sourse));
         Sourse = _sourse;
         EditData = _editdata;
         SignificanceCoefficient = _significancecoefficient;
         IsDeleted = _isdeleted;
         if (_article1с0 == null) throw new ArgumentNullException(nameof(_article1с0));
         _article1с0.ParentArticle = this;

         if (_articletag1 == null) throw new ArgumentNullException(nameof(_articletag1));
         _articletag1.Articles = this;

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="_title"></param>
      /// <param name="_sourse"></param>
      /// <param name="_editdata"></param>
      /// <param name="_significancecoefficient"></param>
      /// <param name="_isdeleted"></param>
      /// <param name="_article1с0"></param>
      /// <param name="_articletag1"></param>
      public static Article1С Create(string _title, string _sourse, DateTime _editdata, double _significancecoefficient, bool _isdeleted, Models.Article1С _article1с0, Models.ArticleTag _articletag1)
      {
         return new Article1С(_title, _sourse, _editdata, _significancecoefficient, _isdeleted, _article1с0, _articletag1);
      }

      // Persistent properties

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string Title { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string Sourse { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public DateTime EditData { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public double SignificanceCoefficient { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public bool IsDeleted { get; set; }

      // Persistent navigation properties

      public virtual Models.Article1С ParentArticle { get; set; }

      public virtual Models.Configuration1C ConfigurationId { get; set; }

   }
}

