//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Infrastructure.Annotations;
using System.Data.Entity;
using  System.ComponentModel.DataAnnotations;

namespace Models
{
   /// <inheritdoc/>
   public partial class EFModel : System.Data.Entity.DbContext
   {
      #region DbSets
      public System.Data.Entity.DbSet<Models.Article1С> Article1С { get; set; }
      public System.Data.Entity.DbSet<Models.ArticleTag> ArticleTag { get; set; }
      public System.Data.Entity.DbSet<Models.Configuration1C> Configuration1C { get; set; }
      public System.Data.Entity.DbSet<Models.Tag> Tag { get; set; }
      #endregion DbSets

      #warning Default constructor not generated for EFModel since no default connection string was specified in the model

      /// <inheritdoc />
      public EFModel(string connectionString) : base(connectionString)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModel>(new EFModelDatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModel(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model) : base(connectionString, model)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModel>(new EFModelDatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModel(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModel>(new EFModelDatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModel(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModel>(new EFModelDatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModel(System.Data.Entity.Infrastructure.DbCompiledModel model) : base(model)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModel>(new EFModelDatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModel(System.Data.Entity.Core.Objects.ObjectContext objectContext, bool dbContextOwnsObjectContext) : base(objectContext, dbContextOwnsObjectContext)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModel>(new EFModelDatabaseInitializer());
         CustomInit();
      }

      partial void CustomInit();
      partial void OnModelCreatingImpl(System.Data.Entity.DbModelBuilder modelBuilder);
      partial void OnModelCreatedImpl(System.Data.Entity.DbModelBuilder modelBuilder);

      /// <inheritdoc />
      protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
      {
         base.OnModelCreating(modelBuilder);
         OnModelCreatingImpl(modelBuilder);

         modelBuilder.HasDefaultSchema("dbo");

         modelBuilder.Entity<Models.Article1С>()
                     .ToTable("Article1С")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<Models.Article1С>()
                     .Property(t => t.Id)
                     .IsRequired()
                     .HasColumnAnnotation("Index", new IndexAnnotation(new IndexAttribute()))
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
         modelBuilder.Entity<Models.Article1С>()
                     .Property(t => t.Title)
                     .IsRequired();
         modelBuilder.Entity<Models.Article1С>()
                     .Property(t => t.Sourse)
                     .IsRequired();
         modelBuilder.Entity<Models.Article1С>()
                     .Property(t => t.EditData)
                     .IsRequired();
         modelBuilder.Entity<Models.Article1С>()
                     .Property(t => t.SignificanceCoefficient)
                     .IsRequired();
         modelBuilder.Entity<Models.Article1С>()
                     .Property(t => t.IsDeleted)
                     .IsRequired();
         modelBuilder.Entity<Models.Article1С>()
                     .HasOptional(x => x.ParentArticle)
                     .WithRequired()
                     .Map(x => x.MapKey("Article1С_Id"));
         modelBuilder.Entity<Models.Article1С>()
                     .HasOptional(x => x.ConfigurationId)
                     .WithRequired()
                     .Map(x => x.MapKey("Article1С1_Id"));

         modelBuilder.Entity<Models.ArticleTag>()
                     .ToTable("ArticleTag")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<Models.ArticleTag>()
                     .Property(t => t.Id)
                     .IsRequired()
                     .HasColumnAnnotation("Index", new IndexAnnotation(new IndexAttribute()))
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
         modelBuilder.Entity<Models.ArticleTag>()
                     .HasOptional(x => x.Tags)
                     .WithRequired()
                     .Map(x => x.MapKey("ArticleTag_Id"));
         modelBuilder.Entity<Models.ArticleTag>()
                     .HasOptional(x => x.Articles)
                     .WithRequired()
                     .Map(x => x.MapKey("ArticleTag1_Id"));

         modelBuilder.Entity<Models.Configuration1C>()
                     .ToTable("Configuration1C")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<Models.Configuration1C>()
                     .Property(t => t.Id)
                     .IsRequired()
                     .HasColumnAnnotation("Index", new IndexAnnotation(new IndexAttribute()))
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

         modelBuilder.Entity<Models.Tag>()
                     .ToTable("Tag")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<Models.Tag>()
                     .Property(t => t.Id)
                     .IsRequired()
                     .HasColumnAnnotation("Index", new IndexAnnotation(new IndexAttribute()))
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

         OnModelCreatedImpl(modelBuilder);
      }
   }
}
