//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace WebApi.EF.Design
{
   public partial class Article
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Article()
      {
         EditDate = DateTime.Now;
         ArticleTag = new System.Collections.Generic.HashSet<WebApi.EF.Design.ArticleTag>();

         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="_title"></param>
      /// <param name="_text"></param>
      /// <param name="_article0"></param>
      public Article(string _title, string _text, WebApi.EF.Design.Article _article0)
      {
         if (string.IsNullOrEmpty(_title)) throw new ArgumentNullException(nameof(_title));
         Title = _title;
         if (string.IsNullOrEmpty(_text)) throw new ArgumentNullException(nameof(_text));
         Text = _text;
         if (_article0 == null) throw new ArgumentNullException(nameof(_article0));
         _article0.ParentArticle = this;

         ArticleTag = new HashSet<WebApi.EF.Design.ArticleTag>();
         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="_title"></param>
      /// <param name="_text"></param>
      /// <param name="_article0"></param>
      public static Article Create(string _title, string _text, WebApi.EF.Design.Article _article0)
      {
         return new Article(_title, _text, _article0);
      }

      // Persistent properties

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string Title { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string Text { get; set; }

      /// <summary>
      /// Default value = DateTime.Now
      /// </summary>
      public DateTime? EditDate { get; set; }

      public double? SignificanceCoefficient { get; set; }

      public bool? IsDeleted { get; set; }

      // Persistent navigation properties

      public virtual WebApi.EF.Design.Article ParentArticle { get; set; }

      public virtual ICollection<WebApi.EF.Design.ArticleTag> ArticleTag { get; set; }

      public virtual WebApi.EF.Design.Configuration1C Configuration1C { get; set; }

   }
}

