//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace WebApi.EF.Design
{
   public partial class OpenedArticle
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected OpenedArticle()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="_article"></param>
      /// <param name="_searchingquery"></param>
      public OpenedArticle(WebApi.EF.Design.Article _article, WebApi.EF.Design.SearchingQuery _searchingquery)
      {
         if (_article == null) throw new ArgumentNullException(nameof(_article));
         Article = _article;

         if (_searchingquery == null) throw new ArgumentNullException(nameof(_searchingquery));
         SearchingQuery = _searchingquery;

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="_article"></param>
      /// <param name="_searchingquery"></param>
      public static OpenedArticle Create(WebApi.EF.Design.Article _article, WebApi.EF.Design.SearchingQuery _searchingquery)
      {
         return new OpenedArticle(_article, _searchingquery);
      }

      // Persistent properties

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      public string OpenedNumber { get; set; }

      public string ListNumber { get; set; }

      public string IsLastOpened { get; set; }

      public string Time { get; set; }

      public string Mark { get; set; }

      // Persistent navigation properties

      /// <summary>
      /// Required
      /// </summary>
      public virtual WebApi.EF.Design.Article Article { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      public virtual WebApi.EF.Design.SearchingQuery SearchingQuery { get; set; }

   }
}

