//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace WebApi.EF.Design
{
   public partial class Provider
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public Provider()
      {
         User = new System.Collections.Generic.HashSet<WebApi.EF.Design.User>();

         Init();
      }

      // Persistent properties

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      public string Name { get; set; }

      public string LogoUrl { get; set; }

      public string ContractEndTime { get; set; }

      // Persistent navigation properties

      public virtual ICollection<WebApi.EF.Design.User> User { get; set; }

   }
}

