//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace WebApi.EF.Design
{
   public partial class Session
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Session()
      {
         SearchingQuery = new System.Collections.Generic.HashSet<WebApi.EF.Design.SearchingQuery>();

         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="_user"></param>
      public Session(WebApi.EF.Design.User _user)
      {
         if (_user == null) throw new ArgumentNullException(nameof(_user));
         User = _user;

         SearchingQuery = new HashSet<WebApi.EF.Design.SearchingQuery>();
         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="_user"></param>
      public static Session Create(WebApi.EF.Design.User _user)
      {
         return new Session(_user);
      }

      // Persistent properties

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      public string OpenTime { get; set; }

      public string CloseTime { get; set; }

      // Persistent navigation properties

      public virtual ICollection<WebApi.EF.Design.SearchingQuery> SearchingQuery { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      public virtual WebApi.EF.Design.User User { get; set; }

   }
}

